name: "Monorepo setup"
description: "Resolve dependency caching and build + start the projects"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      name: Install Node 18
      with:
        node-version: "18"

    - uses: ./.github/actions/pnpm

    - name: Creating .env files
      shell: bash
      run: mv ./websites/frontend/.env.example ./websites/frontend/.env && mv ./websites/backend/.env.example ./websites/backend/.env && mv ./packages/database/.env.example ./packages/database/.env
