name: "Monorepo setup"
description: "Resolve dependency caching and build + start the projects"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      name: Install Node 18
      with:
        node-version: "18"

    - uses: ./.github/actions/pnpm

    - name: Creating .env files
      shell: bash
      run: mv ./packages/frontend/.env.example ./packages/frontend/.env && mv ./packages/backend/.env.example ./packages/backend/.env && mv ./packages/database/.env.example ./packages/database/.env

    - name: Bootstrap projects
      shell: bash
      run: pnpm run setup

    - name: Prepare the DB
      shell: bash
      run: rm -rf ./packages/database/prisma/migrations && pnpm run db:prepare

    - name: Build
      shell: bash
      run: pnpm run build

    - name: Start the backend project
      working-directory: ./packages/backend
      shell: bash
      run: pnpm start &
