FROM node:18 AS builder
WORKDIR /app

RUN apt-get update || : && apt-get install python -y
RUN apt-get install python3-pip -y
RUN npm i -g pnpm

COPY . .

RUN rm -rf examples packages/documentation packages/backend packages/load-testing packages/sdk-node
RUN pnpm install --filter @progressively/frontend...
RUN pnpm run build --filter @progressively/frontend

FROM node:18 AS runner

RUN npm i -g pnpm

COPY --from=builder /app ./

EXPOSE 3000

CMD [ "pnpm", "run", "start:frontend" ]