FROM node:18-bullseye-slim as build
WORKDIR /app
RUN npm i -g pnpm
COPY ./scripts ./scripts
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./packages/backend ./packages/backend
COPY ./packages/shared ./packages/shared
COPY ./packages/database ./packages/database
# Hack to prevent cypress from installing
RUN pnpm install --ignore-scripts --filter @progressively/backend...
RUN pnpm run build --filter @progressively/backend


FROM node:18-bullseye-slim as prodDeps
WORKDIR /app
RUN npm i -g pnpm
COPY --from=build ./app/scripts ./scripts
COPY --from=build ./app/package.json ./package.json
COPY --from=build ./app/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=build ./app/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY --from=build ./app/turbo.json ./turbo.json

COPY --from=build ./app/packages/backend/dist ./packages/frontend/dist
COPY --from=build ./app/packages/backend/package.json ./packages/frontend/package.json

COPY --from=build ./app/packages/shared/dist ./packages/shared/dist
COPY --from=build ./app/packages/shared/package.json ./packages/shared/package.json

COPY --from=build ./app/packages/database/dist ./packages/database/dist
COPY --from=build ./app/packages/database/package.json ./packages/database/package.json
COPY --from=build ./app/packages/database/prisma ./packages/database/prisma
RUN pnpm install --prod
RUN cd packages/database && pnpm run db:generate:schema


FROM node:18-bullseye-slim as runner
WORKDIR /app
RUN npm i -g pnpm
COPY --from=prodDeps /app .
EXPOSE 4000
CMD [ "pnpm", "run", "start:backend" ]

