FROM node:18-bullseye-slim as base
RUN npm i -g pnpm
WORKDIR /app
EXPOSE 3000

FROM base as dev
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=pnpm-lock.yaml,target=pnpm-lock.yaml \
    --mount=type=bind,source=pnpm-workspace.yaml,target=pnpm-workspace.yaml \
    pnpm install --prod
USER node
COPY . .
CMD pnpm turbo run dev --filter=@progressively/frontend
