# fly.toml app configuration file generated for backend-progressively on 2023-05-01T07:13:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-progressively"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
auto_rollback = true

[build]
dockerfile = "Dockerfile.Backend"

[env]
ALLOW_REGISTRATION = "true"
BACKEND_URL = "https://api.progressively.app"
FRONTEND_URL = "https://dashboard.progressively.app"
REFRESH_TOKEN_EXPIRES = "84600"
ACCESS_TOKEN_EXPIRES = "84600"
SMTP_PORT = "587"
SOCKET_TIMEOUT = "10000"
THROTTLING_LIMIT = "10000"
THROTTLING_TTL = "60"

[[services]]
protocol = "tcp"
internal_port = 4000
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "1s"
restart_limit = 0
