name: "Backend setup"
description: "Resolve dependency caching and build + start the projects"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "npm"
        cache-dependency-path: |
          package-lock.json
          packages/frontend/package-lock.json
          packages/backend/package-lock.json

    - name: Creating .env files
      shell: bash
      run: mv ./packages/frontend/.env.example ./packages/frontend/.env && mv ./packages/backend/.env.example ./packages/backend/.env

    - name: Bootstrap projects
      shell: bash
      run: npm run setup:ci

    - name: Prepare the DB
      shell: bash
      run: npm run db:prepare

    - name: Build
      shell: bash
      run: npm run build

    - name: Start the backend project
      working-directory: ./packages/backend
      shell: bash
      run: npm start &
