import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import { ProgressivelyProvider, useFlags } from "@progressively/react";
import { getProgressivelyProps } from "@progressively/react/lib/ssr";

const FlaggedComponent = () => {
  const { flags, track } = useFlags();

  return (
    <main>
      <div>
        <h1>New homepage</h1>
        {flags.newHomepage ? "New variant" : "Old variant"}
      </div>

      <button onClick={() => track("A metric", { hello: "world" })}>
        Click me
      </button>

      <footer>{flags.newFooter ? "New footer" : "Old footer"}</footer>
    </main>
  );
};

const Home: NextPage = ({ progressivelyProps }: any) => {
  return (
    <ProgressivelyProvider {...progressivelyProps}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <FlaggedComponent />
      </div>
    </ProgressivelyProvider>
  );
};

export async function getServerSideProps({
  req,
  res,
}: {
  req: Request;
  res: any;
}) {
  const { progressivelyProps, cookies } = await getProgressivelyProps(
    "valid-sdk-key",
    {
      websocketUrl: "ws://localhost:4000",
      apiUrl: "http://localhost:4000",
      fields: {
        email: "marvin.frachet@something.com",
        id: "1",
      },
    }
  );

  res.setHeader("set-cookie", cookies);

  return {
    props: {
      progressivelyProps,
    },
  };
}

export default Home;
