name: Backend
env:
  SLEEP_DELAY: 0

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  integration-test:
    env:
      IS_SAAS: true
      SEED_ROUND_EVENT_HITS: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testPath: ["flags.e2e", '--testPathIgnorePatterns=".*flags\.e2e.*"']
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: progressively
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: actions/checkout@v2
      - uses: ./.github/actions/monorepo-setup

      - name: Install dependencies
        shell: bash
        run: pnpm install --filter @progressively/backend...

      - name: Build
        shell: bash
        run: pnpm run build --filter @progressively/backend

      - name: Prepare the DB
        shell: bash
        run: rm -rf ./packages/database/prisma/migrations && pnpm run db:prepare

      - name: Start the backend project
        shell: bash
        run: pnpm run start:backend &

      - name: API tests (${{ matrix.testPath }})
        working-directory: ./packages/backend
        run: pnpm run test:e2e ${{ matrix.testPath }}
