name: Backend

env:
  SLEEP_DELAY: 0

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: progressively
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - uses: ./.github/actions/monorepo-setup

      - name: Lint
        working-directory: ./packages/backend
        run: pnpm run lint

      - name: Tests
        working-directory: ./packages/backend
        run: pnpm run test

      - name: API tests
        working-directory: ./packages/backend
        run: pnpm run test:e2e
