name: Documentation
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            packages/frontend/package-lock.json
            packages/backend/package-lock.json

      - name: Install
        run: npm install
        working-directory: ./packages/documentation

      - name: Build the project and start
        run: npm run build
        working-directory: ./packages/documentation

      - name: Start the project
        run: npm start &
        working-directory: ./packages/documentation

      - name: E2E tests
        run: npx wait-on -t 60000 tcp:3000 && npm run test:e2e:ci
        working-directory: ./packages/documentation
