name: Example SDK Php
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: progressively
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/backend-setup

      - name: Install the cypress-helpers dependencies
        working-directory: ./example/cypress-helpers
        run: npm i

      - name: Install dependencies on the example project
        working-directory: ./example/php
        run: npm i && composer install

      - name: Start the Example PHP project
        working-directory: ./example/php
        run: php -S localhost:3000 &

      - name: E2E tests
        working-directory: ./example/php
        run: npx wait-on -t 60000 tcp:4000 && npm run test:e2e:ci
