name: Astro
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: progressively
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pnpm

      - name: Creating .env files
        shell: bash
        run: mv ./packages/frontend/.env.example ./packages/frontend/.env && mv ./packages/backend/.env.example ./packages/backend/.env && mv ./packages/database/.env.example ./packages/database/.env

      - name: Install dependencies
        shell: bash
        run: pnpm install --filter backend --filter database --filter playwright-helpers --filter example-astro

      - name: Build
        shell: bash
        run: pnpm run build --filter backend

      - name: Prepare the DB
        shell: bash
        run: rm -rf ./packages/database/prisma/migrations && pnpm run db:prepare

      - name: Start the backend project
        working-directory: ./packages/backend
        shell: bash
        run: pnpm start &

      - name: Start the Example AstroBuild project
        working-directory: ./example/astro
        run: pnpm start &

      - name: E2E tests
        working-directory: ./example/astro
        run: npx wait-on -t 60000 tcp:4000 && pnpm run test:e2e:ci
