name: Frontend
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: packages/frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./packages/frontend
        run: npm ci --legacy-peer-deps

      - name: Preparation
        working-directory: ./packages/frontend
        run: mv .env.example .env

      - name: Lint
        working-directory: ./packages/frontend
        run: npm run lint

      - name: Tests
        working-directory: ./packages/frontend
        run: npm run test

      - name: Build
        working-directory: ./packages/frontend
        run: npm run build
