name: Frontend
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: ./.github/actions/monorepo-setup

      - name: Lint
        working-directory: ./packages/frontend
        run: pnpm run lint

      - name: Tests
        working-directory: ./packages/frontend
        run: pnpm run test
