name: Publish docker image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Build frontend image
        run: |
          docker build -t marvinfrachet/progressively-frontend -f Dockerfile.Frontend .
          docker tag marvinfrachet/progressively-frontend:latest marvinfrachet/progressively-frontend:${{  github.ref_name }}

      - name: Build backend image
        run: |
          docker build -t marvinfrachet/progressively-backend -f Dockerfile.Backend .
          docker tag marvinfrachet/progressively-backend:latest marvinfrachet/progressively-backend:${{  github.ref_name }}

      - name: Pushing images
        run: |
          docker push marvinfrachet/progressively-frontend:${{  github.ref_name }}
          docker push marvinfrachet/progressively-backend:${{  github.ref_name }}
          docker push marvinfrachet/progressively-frontend:latest
          docker push marvinfrachet/progressively-backend:latest
