name: Publish docker image

on:
  push:
    tags:
      - "v**.**.**apps"

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GitHub Tag Name example
        run: |
          echo "APP_VERSION=$(echo "${{  github.ref_name }}" | sed 's/+apps//' | sed 's/v//')" >> $GITHUB_ENV

      - name: Build frontend image
        run: |
          docker build -t marvinfrachet/progressively-frontend -f Dockerfile.Frontend .
          docker tag marvinfrachet/progressively-frontend:latest marvinfrachet/progressively-frontend:${APP_VERSION}

      - name: Build backend image
        run: |
          docker build -t marvinfrachet/progressively-backend -f Dockerfile.Backend .
          docker tag marvinfrachet/progressively-backend:latest marvinfrachet/progressively-backend:${APP_VERSION}

      - name: Check image tags
        run: |
          docker images

      - name: Pushing images
        run: |
          docker push marvinfrachet/progressively-frontend:${APP_VERSION}
          docker push marvinfrachet/progressively-backend:${APP_VERSION}
          docker push marvinfrachet/progressively-frontend:latest
          docker push marvinfrachet/progressively-backend:latest
