name: Sdk React
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - uses: ./.github/actions/monorepo-setup

      - name: Tests
        working-directory: ./packages/react
        run: pnpm run test

      - name: Bundlesize
        working-directory: ./packages/react
        run: pnpm run bundlesize
