name: Sdk
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: packages/sdk-js/package-lock.json

      - name: Bootstrap projects
        shell: bash
        run: npm run setup

      - name: Build projects
        shell: bash
        run: npm run build

      - name: Tests
        working-directory: ./packages/sdk-js
        run: npm run test

      - name: Bundlesize
        working-directory: ./packages/sdk-js
        run: npm run bundlesize
