name: Shared checks (build, lint, tests, bundlesize)
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - uses: actions/checkout@v2
      - uses: ./.github/actions/monorepo-setup
      - uses: ./.github/actions/clickhouse

      - name: Bootstrap projects
        shell: bash
        run: pnpm run setup

      - name: Shared checks
        shell: bash
        run: pnpm run ci:shared:checks
